### ISSUE TITLE
Thoughts on Tetris Time

### ISSUE THREAD

**Issue by vpmaster2004** [toblum/esp_p10_tetris_clock#1]
I have a few ideas

If you know how to create apps for Android and/or iOS, you could create something that controls the clock from your phone.
How about adding some alarm & countdown timer capabilities with animations that happen when time is expired. Maybe even add the ability to upload custom timer & alarm sounds. 
World Time, maybe?
Does the clock have the ability to let the user play Tetris itself?
If I have more ideas, I'll post them here.

**Comment by toblum** [comment]
Hi @vpmaster2004,

thank you for your feedback. 
Native apps are really a lot of work and quite expensive if you want to publish them in the app store. So I probably won't build one.
But what the watch will definitely get is a web interface with which you can make timezone and other settings, even from your mobile phone.
Using it as a timer is a nice idea. I'll put it on my list of possible enhancements.
Sound is also a option, I will see.
There is no tetris game option, but I heard that other makers are working on this.

Feel free to contact me if you have any issues.

Best regards
Tobias
