### ISSUE TITLE
Wrong LED Matrix Size

### ISSUE THREAD

**Issue by BCChad** [toblum/esp_p10_tetris_clock#3]
Tobias - the name of this project is "P10" tetris clock.  A P10 display is 160 x 320 mm, however the Adafruit Matrix you cited, the wood frame, and the 3D parts are sized more to fit 96 x 192 mm , which I believe is the "P6" sized matrix.
Please correct me if I'm wrong, however I did purchase the P10 matrix, and unfortunately went to the expense of 3D printing the grid according to the drawings provided, which clearly are too small for the P10.  Did I read something incorrectly?

**Comment by toblum** [comment]
Hi Chad,

sorry for the confusion. You're right, but it's easy to explain. The first build was based on a P10 matrix (10 mm pitch size) as in the pixel time project (https://2dom.github.io/PixelTime/). That board died and I had to use another one so I swapped it for the P6 but I had already chosen the name and repository (which can't be changed afterwards) so I left it as it works with all pitch sizes the same way. 
I now added some notes in the parts list to clearify this.
BTW: There is also a "true P10" grid here: https://www.thingiverse.com/thing:2668845

Best regards
Tobias
