### ISSUE TITLE
Support for 64x32

### ISSUE THREAD

**Issue by raymiec** [toblum/esp_p10_tetris_clock#5]
Would be sweet, it almost works in 32x32, some lines are off.

but full use of the matrix would be nice.

**Comment by toblum** [comment]
Hi @raymiec,

please also have a look at the https://github.com/toblum/TetrisAnimation repo. It's a improved version as a library. Brian has also a video on it: https://www.youtube.com/watch?v=2IejVgrSlWE He used it on a 64x32 matrix.

Regards
Tobias
